---
title: Voeg effen of gestippelde randen toe
hero_image: images/banner.png
description: Voeg effen of gestippelde randen toe aan elementen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Voeg effen of gestippelde randen toe
