title: Ajouter des bordures pleines ou en pointillés
hero_image: images/banner.png
description: Ajoute des bordures pleines ou en pointillés aux éléments.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ajouter des bordures pleines ou en pointillés
